name: flutter_secure_storage_x
repository: https://github.com/koji-1009/flutter_secure_storage

packages:
  - flutter_secure_storage_x
  - flutter_secure_storage_x/example
  - flutter_secure_storage_x_linux
  - flutter_secure_storage_x_macos
  - flutter_secure_storage_x_platform_interface
  - flutter_secure_storage_x_web
  - flutter_secure_storage_x_windows
  - flutter_secure_storage_x_windows/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: true

  bootstrap:
    usePubspecOverrides: true

    environment:
      sdk: '>=3.4.0 <4.0.0'
      flutter: '>=3.22.0'
    dependencies:
      win32: '^5.5.1'
