name: flutter_secure_storage_x
repository: https://github.com/koji-1009/flutter_secure_storage

packages:
  - flutter_secure_storage_x
  - flutter_secure_storage_x/example
  - flutter_secure_storage_x_linux
  - flutter_secure_storage_x_macos
  - flutter_secure_storage_x_platform_interface
  - flutter_secure_storage_x_web
  - flutter_secure_storage_x_windows
  - flutter_secure_storage_x_windows/example

command:
  bootstrap:
    environment:
      sdk: '>=3.4.0 <4.0.0'
      flutter: '>=3.22.0'
    dependencies:
      ffi: ^2.0.0
      path: ^1.8.0
      path_provider: ^2.0.0
      platform: ^3.0.0
      web: '>=0.5.0 <2.0.0'
      win32: ^5.5.1
    dev_dependencies:
      flutter_lints: ^5.0.0
