name: flutter_secure_storage_x_macos
description: macOS implementation of flutter_secure_storage
repository: https://github.com/koji-1009/flutter_secure_storage/tree/main/flutter_secure_storage_x_macos
version: 3.1.2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_x_platform_interface: ^1.1.2

flutter:
  plugin:
    implements: flutter_secure_storage_x
    platforms:
      macos:
        pluginClass: FlutterSecureStoragePlugin
