name: flutter_secure_storage_x_platform_interface
description: A common platform interface for the flutter_secure_storage plugin.
repository: https://github.com/koji-1009/flutter_secure_storage/tree/main/flutter_secure_storage_x_platform_interface
version: 1.2.0

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0
  mockito: ^5.0.12